services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      -  "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234